hey-url-challenge-code-dotnet/ViewModels/ErrorViewModel.cs
namespace HeyUrlChallengeCodeDotnet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

hey-url-challenge-code-dotnet/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using hey_url_Model;

namespace hey_url_challenge_code_dotnet.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Url> Urls { get; set; }
        public Url NewUrl { get; set; }
    }
}

hey-url-challenge-code-dotnet/ViewModels/ShowViewModel.cs
using System.Collections.Generic;
using hey_url_Model;

namespace hey_url_challenge_code_dotnet.ViewModels
{
    public class ShowViewModel
    {
        public Url Url { get; set; }
        public Dictionary<string, int> DailyClicks { get; set; }
        public Dictionary<string, int> BrowseClicks { get; set; }
        public Dictionary<string, int> PlatformClicks { get; set; }
        public Dictionary<string, int> BrowsePlatformClicks { get; set; }
    }
}

hey-url-challenge-code-dotnet/Controllers/UrlsController.cs
using System;
using System.Collections.Generic;
using hey_url_Model;
using hey_url_Service;
using hey_url_challenge_code_dotnet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shyjus.BrowserDetection;
using hey_url_Service.Interfaces;
using hey_url_challenge_code_dotnet.Helper;

namespace HeyUrlChallengeCodeDotnet.Controllers
{
    [Route("/")]
    public class UrlsController : Controller
    {
        private readonly ILogger<UrlsController> _logger;
        private static readonly Random getrandom = new Random();
        private readonly IBrowserDetector browserDetector;
        public IUrlService urlService;
        public IUrlClickService urlClickService;

        public UrlsController(ILogger<UrlsController> logger, IBrowserDetector browserDetector, IUrlService urlservice, IUrlClickService urlclickservice)
        {
            this.browserDetector = browserDetector;
            this.urlService = urlservice;
            this.urlClickService = urlclickservice;
            _logger = logger;
        }

        public IActionResult Index()
        {
            try
            {
                var model = new HomeViewModel();
                model.Urls = urlService.GetAll(-1);
                model.NewUrl = new();
                ViewBag.baseurl = GlobalValues.BaseUrl;
                return View(model);
            }
            catch (Exception ex)
            {
                //log exception
                return BadRequest();
            }
        }

        [Route("/{url}")]
        public IActionResult Visit(string url)
        {
            try
            {
                Url UrlVisited = this.urlService.Get(url);
                if (UrlVisited == null)
                {
                    return new NotFoundResult();
                }
                UrlClick newrecord = new UrlClick();
                newrecord.Url = UrlVisited;
                newrecord.UrlId = UrlVisited.UrlId;
                newrecord.Browser = this.browserDetector.Browser.Name;
                newrecord.Platform = this.browserDetector.Browser.OS;
                this.urlClickService.Add(newrecord);
                return Redirect(UrlVisited.OrinalUrl);
            }
            catch (Exception ex)
            {
                //log exception
                return new BadRequestResult();
            }
        }

        [Route("urls/{urlid}")]
        public IActionResult Show(int urlid)
        {
            try
            {
                ShowViewModel model = new ShowViewModel();
                model.Url = this.urlService.Get(urlid);
                model.BrowseClicks = this.urlClickService.GetReportBrowsers(urlid);
                model.PlatformClicks = this.urlClickService.GetReportPlatform(urlid);
                model.BrowsePlatformClicks = this.urlClickService.GetReportPlatformBrowsers(urlid);
                model.DailyClicks = this.urlClickService.GetDailyClicks(urlid);
                return View("Show", model);
            }
            catch (Exception ex)
            {
                //log exception
                return new BadRequestResult();
            }
        }

        [HttpPost]
        public IActionResult Create(HomeViewModel model)
        {
            try
            {
                model.NewUrl.ShortUrl = "";
                model.NewUrl.CretionDate = DateTime.Now;
                model.NewUrl.Count = 0;
                this.urlService.Add(model.NewUrl);
                model.NewUrl.ShortUrl = GlobalValues.BaseUrl +   model.NewUrl.ShortUrl;
                return PartialView("create", model.NewUrl);
            }
            catch
            {
                //log exception
                return new BadRequestResult();
            }
        }

    }
}

hey-url-challenge-code-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" />
    <script src="~/lib/materialize/js/materialize.min.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <a class="brand-logo" asp-area="" asp-controller="Urls" asp-action="Index">HeyURL!</a>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

hey-url-challenge-code-dotnet/Views/Urls/Create.cshtml
@model hey_url_Model.Url

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <h4>Congratulations !!! your URL has been shortened</h4>
    <hr />
    <dl class="row">
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortUrl)
        </dt>
        <dd class="col-sm-10">
            <a href="@Html.DisplayFor(model => model.ShortUrl)">@Html.DisplayFor(model => model.ShortUrl)</a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrinalUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrinalUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CretionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CretionDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

hey-url-challenge-code-dotnet/Views/Urls/Index.cshtml
@model hey_url_challenge_code_dotnet.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

@if (TempData["Notice"] is not null)
{
    <div class="card-panel notice deep-orange">@TempData["Notice"]</div>
}

<div class="row">
    <div class="col m12">
        <form asp-action="Create">
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col m8 offset-m2 center-align">
                            <span class="card-title">Create a new short URL</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m6 offset-m2">
                            @Html.EditorFor(m => m.NewUrl.OrinalUrl)
                            @Html.ValidationMessageFor(v => v.NewUrl.OrinalUrl)                            
                        </div>
                        <div class="col m2">
                            <button type="submit" class="btn">Shorten URL</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<table class="table highlight">
    <thead>
        <tr>
            <th scope="col">Short URL</th>
            <th scope="col">Original URL</th>
            <th scope="col">Created</th>
            <th scope="col">Clicks Count</th>
            <th scope="col">Stats</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var url in Model.Urls)
        {
            <tr>
                <th scope="row"><a href="@string.Format("{0}{1}",ViewBag.baseurl,url.ShortUrl)">@string.Format("{0}{1}", ViewBag.baseurl, url.ShortUrl)</a></th>
                <td><a href="@url.OrinalUrl">@url.OrinalUrl</a></td>
                <td><!-- Please match the same format -->@url.CretionDate.ToString("MMM dd, yyyy")</td>
                <td>@url.Count</td>
                <td>
                    <a href=@string.Format("/urls/{0}", url.UrlId.ToString())>
                        <svg class="octicon octicon-graph" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
                            <path fill-rule="evenodd" d="M16 14v1H0V0h1v14h15zM5 13H3V8h2v5zm4 0H7V3h2v10zm4 0h-2V6h2v7z"></path>
                        </svg>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

hey-url-challenge-code-dotnet/Views/Urls/Show.cshtml
@model hey_url_challenge_code_dotnet.ViewModels.ShowViewModel

@{
    ViewBag.Title = "Show";
    Layout = "_Layout";
}

<div class="row">
    <div class="col s12">
        <ul class="card-panel collection with-header">
            <li class="collection-header">
                <h4>
                    Stats for <a href="@Model.Url.ShortUrl">@Model.Url.ShortUrl</a>
                </h4>
            </li>
            <li class="collection-item">Created @Model.Url.CretionDate.ToString("MMM dd, yyyy") </li>
            <li class="collection-item">
                Original URL: @Model.Url.OrinalUrl
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col s12">
        <div class="card-panel">
            <div id="total-clicks-chart"></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col s6">
        <div class="card-panel">
            <div id="platforms-chart"></div>
        </div>
    </div>

    <div class="col s6">
        <div class="card-panel">
            <div id="browsers-chart"></div>
        </div>
    </div>

    <div class="col s6">
        <div class="card-panel">
            <div id="Browser_Platform_chart"></div>
        </div>
    </div>

</div>

<script>
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(drawCharts);
    function drawTotalClicksChart() {
      var data = google.visualization.arrayToDataTable([
        ['day', 'clicks'],
      ].concat(@Json.Serialize(Model.DailyClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'total clicks',
        haxis: {
          title: 'day of month'
        },
        vaxis: {
          title: 'clicks'
        }
      };
      var chart = new google.visualization.AreaChart(
        document.getElementById('total-clicks-chart')
      );
      chart.draw(data, options);
    }
    function drawBrowsersChart() {
      var data = google.visualization.arrayToDataTable([
        ['browser', 'clicks'],
      ].concat(@Json.Serialize(Model.BrowseClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'Browsers'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('browsers-chart')
      );
      chart.draw(data, options);
    }
    function drawPlatformsChart() {
      var data = google.visualization.arrayToDataTable([
        ['platform', 'clicks'],
      ].concat(@Json.Serialize(Model.PlatformClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'Platform'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('platforms-chart')
      );
      chart.draw(data, options);
      }

      function drawPlatformsBrowserChart() {
      var data = google.visualization.arrayToDataTable([
        ['Browser_Platform', 'clicks'],
      ].concat(@Json.Serialize(Model.BrowsePlatformClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
          title: 'Browser_Platform'
      };
      var chart = new google.visualization.PieChart(
          document.getElementById('Browser_Platform_chart')
      );
      chart.draw(data, options);
    }


    function drawCharts() {
      drawTotalClicksChart();
      drawBrowsersChart();
      drawPlatformsChart();
      drawPlatformsBrowserChart();
    }
</script>